### ISSUE TITLE
Error on player join when using MySQL database and streaks disabled

### ISSUE THREAD

**Issue by PlanetTeamSpeakk** [minecrafter/SuperbVote#122]
Whenever a player joins the server, an error is thrown and printed to the console. It doesn't cause any other issues, but should be fixed nonetheless. According to the error message and its stacktrace, it appears that this error is caused by the plugin not checking whether streaks are enabled or not when a player joins. The error in question looks as follows:
```
[13:42:22 WARN]: [SuperbVote] Plugin SuperbVote v0.5.5 generated an exception while executing task 2503910
java.lang.IllegalArgumentException: streaks not enabled
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.16.5.jar:git-Paper-579]
        at io.minimum.minecraft.superbvote.storage.MysqlVoteStorage.getVoteStreak(MysqlVoteStorage.java:369) ~[?:?]
        at io.minimum.minecraft.superbvote.storage.VoteStorage.getVoteStreakIfSupported(VoteStorage.java:25) ~[?:?]
        at io.minimum.minecraft.superbvote.votes.SuperbVoteListener.lambda$onPlayerJoin$4(SuperbVoteListener.java:139) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-579]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-579]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-579]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
```

**Comment by BrainStone** [comment]
It would be interesting to know how to enable streaks btw.

The default config contains nothing about it.
Also the streams table can't be renamed!

**Comment by 100petr** [comment]
https://github.com/astei/SuperbVote/wiki/Configuration#if
![image](https://user-images.githubusercontent.com/29830635/118172477-b6996900-b42c-11eb-9df5-cd2990e3c5bd.png)

**Comment by zachduda** [comment]
Would also like to add that I'm having the same problem with SuperbVote

**Comment by BrainStone** [comment]
> 
> 
> https://github.com/astei/SuperbVote/wiki/Configuration#if
> ![image](https://user-images.githubusercontent.com/29830635/118172477-b6996900-b42c-11eb-9df5-cd2990e3c5bd.png)

Nothing about what you posted is about streaks.  
You posted the docs for the cumulative (aka total) votes.

**Comment by 100petr** [comment]
![image](https://user-images.githubusercontent.com/29830635/118293849-62e55900-b4da-11eb-85af-b444ababfea9.png)
and last message and somehow it could be done, but probably the function doesn't work at all, because it gives an error about the database

**Comment by viveleroi** [comment]
I'm pretty sure this error has broken our vote rewards from being registered properly. No one has been getting vote rewards after we updated to the version that has this change. Nothing about the streaks appears in our config file, so I can't even turn it on.
