### ISSUE TITLE
The plugin say that i don't have storage

### ISSUE THREAD

**Issue by Apiz05** [minecrafter/SuperbVote#129]
Can some one help me this thing keep spamming and crash my server 
```
[22:55:15 WARN]: [SuperbVote] Plugin SuperbVote v0.5.5 generated an exception while executing task 41
java.lang.RuntimeException: Unable to save votes to plugins/SuperbVote/votes.json
        at io.minimum.minecraft.superbvote.storage.JsonVoteStorage.save(JsonVoteStorage.java:232) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.1.jar:git-Purpur-1270]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Purpur-1270]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Purpur-1270]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.nio.file.FileSystemException: /tmp/superbvote-5330387557135517176.json -> plugins/SuperbVote/votes.json: No space left on device
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:100) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
        at sun.nio.fs.UnixCopyFile.copyFile(UnixCopyFile.java:256) ~[?:?]
        at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:491) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:267) ~[?:?]
        at java.nio.file.Files.move(Files.java:1426) ~[?:?]
        at io.minimum.minecraft.superbvote.storage.JsonVoteStorage.save(JsonVoteStorage.java:230) ~[?:?]
        ... 6 more
[22:55:15 WARN]: [SuperbVote] Plugin SuperbVote v0.5.5 generated an exception while executing task 42
java.lang.RuntimeException: Unable to save queued votes to plugins/SuperbVote/queued_votes.json
        at io.minimum.minecraft.superbvote.storage.QueuedVotesStorage.save(QueuedVotesStorage.java:76) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.1.jar:git-Purpur-1270]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Purpur-1270]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Purpur-1270]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.nio.file.FileSystemException: /tmp/superbvote-13433677299785301401.json -> plugins/SuperbVote/queued_votes.json: No space left on device
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:100) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
        at sun.nio.fs.UnixCopyFile.copyFile(UnixCopyFile.java:256) ~[?:?]
        at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:491) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:267) ~[?:?]
        at java.nio.file.Files.move(Files.java:1426) ~[?:?]
        at io.minimum.minecraft.superbvote.storage.QueuedVotesStorage.save(QueuedVotesStorage.java:74) ~[?:?]
        ... 6 more
[22:55:45 WARN]: [SuperbVote] Plugin SuperbVote v0.5.5 generated an exception while executing task 41
java.lang.RuntimeException: Unable to save votes to plugins/SuperbVote/votes.json
        at io.minimum.minecraft.superbvote.storage.JsonVoteStorage.save(JsonVoteStorage.java:232) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.1.jar:git-Purpur-1270]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Purpur-1270]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Purpur-1270]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.nio.file.FileSystemException: /tmp/superbvote-15060339995675676453.json -> plugins/SuperbVote/votes.json: No space left on device
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:100) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
        at sun.nio.fs.UnixCopyFile.copyFile(UnixCopyFile.java:256) ~[?:?]
        at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:491) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:267) ~[?:?]
        at java.nio.file.Files.move(Files.java:1426) ~[?:?]
        at io.minimum.minecraft.superbvote.storage.JsonVoteStorage.save(JsonVoteStorage.java:230) ~[?:?]
        ... 6 more
[22:55:45 WARN]: [SuperbVote] Plugin SuperbVote v0.5.5 generated an exception while executing task 42
java.lang.RuntimeException: Unable to save queued votes to plugins/SuperbVote/queued_votes.json
        at io.minimum.minecraft.superbvote.storage.QueuedVotesStorage.save(QueuedVotesStorage.java:76) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.1.jar:git-Purpur-1270]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Purpur-1270]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Purpur-1270]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.nio.file.FileSystemException: /tmp/superbvote-13791118025899155665.json -> plugins/SuperbVote/queued_votes.json: No space left on device
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:100) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
        at sun.nio.fs.UnixCopyFile.copyFile(UnixCopyFile.java:256) ~[?:?]
        at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:491) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:267) ~[?:?]
        at java.nio.file.Files.move(Files.java:1426) ~[?:?]
        at io.minimum.minecraft.superbvote.storage.QueuedVotesStorage.save(QueuedVotesStorage.java:74) ~[?:?]
        ... 6 more
```

![image](https://user-images.githubusercontent.com/80612886/137649119-2ddb31b0-2d42-47d4-8754-234c5ee7648b.png)

**Comment by astei** [comment]
Perhaps because there is no space left. Clean some up or get in touch with your host, this is not our issue.
