### ISSUE TITLE
 java.io.IOException: No space left on device

### ISSUE THREAD

**Issue by phoenixztt** [minecrafter/SuperbVote#136]
Plugin was running fine for months then started doing this with no changes to it, config, server version, etc. It is not saving vote totals but is still giving rewards.Here is the error it's throwing. The rest of the server is running fine and is not out of storage. 

```10:28:55] [Craft Scheduler Thread - 975 - SuperbVote/WARN]: [SuperbVote] Plugin SuperbVote v0.5.5 generated an exception while executing task 3561408
com.google.gson.JsonIOException: java.io.IOException: No space left on device
	at com.google.gson.Gson.toJson(Gson.java:706) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
	at com.google.gson.Gson.toJson(Gson.java:683) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
	at com.google.gson.Gson.toJson(Gson.java:658) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
	at io.minimum.minecraft.superbvote.storage.QueuedVotesStorage.save(QueuedVotesStorage.java:71) ~[SuperbVote-0.5.5.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
	Suppressed: java.io.IOException: No space left on device
		at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[?:?]
		at sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:62) ~[?:?]
		at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:132) ~[?:?]
		at sun.nio.ch.IOUtil.write(IOUtil.java:97) ~[?:?]
		at sun.nio.ch.IOUtil.write(IOUtil.java:67) ~[?:?]
		at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:288) ~[?:?]
		at java.nio.channels.Channels.writeFullyImpl(Channels.java:74) ~[?:?]
		at java.nio.channels.Channels.writeFully(Channels.java:96) ~[?:?]
		at java.nio.channels.Channels$1.write(Channels.java:171) ~[?:?]
		at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234) ~[?:?]
		at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:340) ~[?:?]
		at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:169) ~[?:?]
		at java.io.OutputStreamWriter.close(OutputStreamWriter.java:252) ~[?:?]
		at java.io.BufferedWriter.close(BufferedWriter.java:269) ~[?:?]
		at io.minimum.minecraft.superbvote.storage.QueuedVotesStorage.save(QueuedVotesStorage.java:70) ~[SuperbVote-0.5.5.jar:?]
		at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
		at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
		at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
		at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.io.IOException: No space left on device
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[?:?]
	at sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:62) ~[?:?]
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:132) ~[?:?]
	at sun.nio.ch.IOUtil.write(IOUtil.java:97) ~[?:?]
	at sun.nio.ch.IOUtil.write(IOUtil.java:67) ~[?:?]
	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:288) ~[?:?]
	at java.nio.channels.Channels.writeFullyImpl(Channels.java:74) ~[?:?]
	at java.nio.channels.Channels.writeFully(Channels.java:96) ~[?:?]
	at java.nio.channels.Channels$1.write(Channels.java:171) ~[?:?]
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234) ~[?:?]
	at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:304) ~[?:?]
	at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282) ~[?:?]
	at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:132) ~[?:?]
	at java.io.OutputStreamWriter.write(OutputStreamWriter.java:205) ~[?:?]
	at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:120) ~[?:?]
	at java.io.BufferedWriter.write(BufferedWriter.java:233) ~[?:?]
	at com.google.gson.stream.JsonWriter.string(JsonWriter.java:590) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
	at com.google.gson.stream.JsonWriter.writeDeferredName(JsonWriter.java:401) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
	at com.google.gson.stream.JsonWriter.value(JsonWriter.java:416) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
	at com.google.gson.internal.bind.TypeAdapters$24.write(TypeAdapters.java:557) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
	at com.google.gson.internal.bind.TypeAdapters$24.write(TypeAdapters.java:546) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
	at com.google.gson.internal.bind.ObjectTypeAdapter.write(ObjectTypeAdapter.java:107) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:208) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
	at com.google.gson.Gson.toJson(Gson.java:704) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
	... 9 more
[10:28:55] [Craft Scheduler Thread - 979 - SuperbVote/WARN]: [SuperbVote] Plugin SuperbVote v0.5.5 generated an exception while executing task 3561407
com.google.gson.JsonIOException: java.io.IOException: No space left on device
	at com.google.gson.Gson.toJson(Gson.java:706) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
	at com.google.gson.Gson.toJson(Gson.java:683) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
	at com.google.gson.Gson.toJson(Gson.java:658) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
	at io.minimum.minecraft.superbvote.storage.JsonVoteStorage.save(JsonVoteStorage.java:227) ~[SuperbVote-0.5.5.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
	Suppressed: java.io.IOException: No space left on device
		at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[?:?]
		at sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:62) ~[?:?]
		at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:132) ~[?:?]
		at sun.nio.ch.IOUtil.write(IOUtil.java:97) ~[?:?]
		at sun.nio.ch.IOUtil.write(IOUtil.java:67) ~[?:?]
		at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:288) ~[?:?]
		at java.nio.channels.Channels.writeFullyImpl(Channels.java:74) ~[?:?]
		at java.nio.channels.Channels.writeFully(Channels.java:96) ~[?:?]
		at java.nio.channels.Channels$1.write(Channels.java:171) ~[?:?]
		at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234) ~[?:?]
		at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:340) ~[?:?]
		at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:169) ~[?:?]
		at java.io.OutputStreamWriter.close(OutputStreamWriter.java:252) ~[?:?]
		at java.io.BufferedWriter.close(BufferedWriter.java:269) ~[?:?]
		at io.minimum.minecraft.superbvote.storage.JsonVoteStorage.save(JsonVoteStorage.java:226) ~[SuperbVote-0.5.5.jar:?]
		at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
		at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
		at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
		at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.io.IOException: No space left on device
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[?:?]
	at sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:62) ~[?:?]
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:132) ~[?:?]
	at sun.nio.ch.IOUtil.write(IOUtil.java:97) ~[?:?]
	at sun.nio.ch.IOUtil.write(IOUtil.java:67) ~[?:?]
	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:288) ~[?:?]
	at java.nio.channels.Channels.writeFullyImpl(Channels.java:74) ~[?:?]
	at java.nio.channels.Channels.writeFully(Channels.java:96) ~[?:?]
	at java.nio.channels.Channels$1.write(Channels.java:171) ~[?:?]
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234) ~[?:?]
	at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:304) ~[?:?]
	at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282) ~[?:?]
	at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:132) ~[?:?]
	at java.io.OutputStreamWriter.write(OutputStreamWriter.java:205) ~[?:?]
	at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:120) ~[?:?]
	at java.io.BufferedWriter.write(BufferedWriter.java:233) ~[?:?]
	at com.google.gson.stream.JsonWriter.string(JsonWriter.java:590) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
	at com.google.gson.stream.JsonWriter.writeDeferredName(JsonWriter.java:401) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
	at com.google.gson.stream.JsonWriter.value(JsonWriter.java:416) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
	at com.google.gson.internal.bind.TypeAdapters$16.write(TypeAdapters.java:409) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
	at com.google.gson.internal.bind.TypeAdapters$16.write(TypeAdapters.java:393) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:208) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
	at com.google.gson.Gson.toJson(Gson.java:704) ~[patched_1.17.1.jar:git-Pufferfish-"9636f36"]
	... 9 more
```

**Comment by Kyrobi** [comment]
Hello, I have just encountered the same issue. Were you able to find a fix or figure out what caused it?
