### ISSUE TITLE
Unable to disable messages per-reward

### ISSUE THREAD

**Issue by frash23** [minecrafter/SuperbVote#2]
**Steps to reproduce**
Remove a player-message or broadcast-message (or set one to null, false, etc) from the config's reward section and restart the server or run /sv reload

**Issue**
The plugin throws an error like so:
```
[09:39:27 ERROR]: Error occurred while enabling SuperbVote v0.3.1 (Is it up to date?)
java.lang.IllegalArgumentException: Section 'player-message' (under ) doesn't contain a valid message section.
        at io.minimum.minecraft.superbvote.configuration.message.VoteMessages.from(VoteMessages.java:13) ~[?:?]
        at io.minimum.minecraft.superbvote.configuration.SuperbVoteConfiguration.deserializeReward(SuperbVoteConfiguration.java:99) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_74]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_74]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_74]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_74]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_74]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_74]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_74]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_74]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_74]
        at io.minimum.minecraft.superbvote.configuration.SuperbVoteConfiguration.<init>(SuperbVoteConfiguration.java:65) ~[?:?]
        at io.minimum.minecraft.superbvote.SuperbVote.onEnable(SuperbVote.java:47) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[patched_1.9.2.jar:git-Paper-647]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:319) [patched_1.9.2.jar:git-Paper-647]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.9.2.jar:git-Paper-647]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:357) [patched_1.9.2.jar:git-Paper-647]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:317) [patched_1.9.2.jar:git-Paper-647]
        at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:412) [patched_1.9.2.jar:git-Paper-647]
        at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:377) [patched_1.9.2.jar:git-Paper-647]
        at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331) [patched_1.9.2.jar:git-Paper-647]
        at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:273) [patched_1.9.2.jar:git-Paper-647]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:571) [patched_1.9.2.jar:git-Paper-647]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
```
(this is the entire stacktrace)

**Issue 2**
If a message is set to an empty string, i.e. `broadcast-message: ''`, it will still broadcast an empty line.

I'm using the latest stable build from Spigot.

**Comment by minecrafter** [comment]
Already fixed in 68a0eff4. You still have to specify a `player-message` but you can turn it off in the configuration.
