### ISSUE TITLE
There's an Error

### ISSUE THREAD

**Issue by juliu123** [minecrafter/SuperbVote#23]
[09:42:34 INFO]: [SuperbVote] Enabling SuperbVote v0.3.4
[09:42:34 ERROR]: Error occurred while enabling SuperbVote v0.3.4 (Is it up to date?)
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.Gson.fromJson(Gson.java:899) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at com.google.gson.Gson.fromJson(Gson.java:852) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at io.minimum.minecraft.superbvote.storage.JsonVoteStorage.<init>(JsonVoteStorage.java:27) ~[?:?]
        at io.minimum.minecraft.superbvote.configuration.SuperbVoteConfiguration.initializeVoteStorage(SuperbVoteConfiguration.java:166) ~[?:?]
        at io.minimum.minecraft.superbvote.SuperbVote.onEnable(SuperbVote.java:49) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:374) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:323) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        ... 15 more

[SuperbVote MyConfig.zip](https://github.com/minecrafter/SuperbVote/files/1386028/SuperbVote.MyConfig.zip)

If I Delete The Vote.json, This Error Will Not Show

**Comment by astei** [comment]
Closing due to inactivity and issue resolved. I will need to find a way to make file corruption happen less often.
