### ISSUE TITLE
bug upon startup

### ISSUE THREAD

**Issue by RainOfPain125** [minecrafter/SuperbVote#31]
[22:00:07 WARN]: [SuperbVote] Plugin SuperbVote v0.3.4 generated an exception while executing task 151
java.util.concurrent.CompletionException: java.io.IOException: Server returned HTTP response code: 503 for URL: https://api.mojang.com/user/profiles/e81a4a299e7a4a2484d9d1038f58bd5c/names
        at io.minimum.minecraft.superbvote.caffeine.cache.BoundedLocalCache$BoundedLocalLoadingCache.lambda$new$0(BoundedLocalCache.java:2921) ~[?:?]
        at io.minimum.minecraft.superbvote.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$15(BoundedLocalCache.java:1800) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap.compute(Unknown Source) ~[?:1.8.0_161]
        at io.minimum.minecraft.superbvote.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:1798) ~[?:?]
        at io.minimum.minecraft.superbvote.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:1781) ~[?:?]
        at io.minimum.minecraft.superbvote.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:97) ~[?:?]
        at io.minimum.minecraft.superbvote.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:66) ~[?:?]
        at io.minimum.minecraft.superbvote.uuid.OnlineModeUuidCache.getNameFromUuid(OnlineModeUuidCache.java:84) ~[?:?]
        at io.minimum.minecraft.superbvote.configuration.message.placeholder.SuperbVotePlaceholderProvider.applyForReminder(SuperbVotePlaceholderProvider.java:36) ~[?:?]
        at io.minimum.minecraft.superbvote.configuration.message.PlainStringMessage.getWithOfflinePlayer(PlainStringMessage.java:40) ~[?:?]
        at io.minimum.minecraft.superbvote.commands.SuperbVoteCommand.lambda$onCommand$1(SuperbVoteCommand.java:138) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.2.jar:git-Paper-1305]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.2.jar:git-Paper-1305]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.2.jar:git-Paper-1305]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_161]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.io.IOException: Server returned HTTP response code: 503 for URL: https://api.mojang.com/user/profiles/e81a4a299e7a4a2484d9d1038f58bd5c/names
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_161]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_161]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source) ~[?:1.8.0_161]
        at io.minimum.minecraft.superbvote.uuid.NameFetcher.nameHistoryFromUuid(NameFetcher.java:26) ~[?:?]
        at io.minimum.minecraft.superbvote.uuid.OnlineModeUuidCache.lambda$new$1(OnlineModeUuidCache.java:36) ~[?:?]
        at io.minimum.minecraft.superbvote.caffeine.cache.BoundedLocalCache$BoundedLocalLoadingCache.lambda$new$0(BoundedLocalCache.java:2914) ~[?:?]
        ... 16 more

**Comment by minecrafter** [comment]
This issue is fixed in 0.4.
