### ISSUE TITLE
Random startup error

### ISSUE THREAD

**Issue by RainOfPain125** [minecrafter/SuperbVote#37]
[16:29:59 INFO]: [SuperbVote] Enabling SuperbVote v0.4-BETA

[16:29:59 WARN]: [SuperbVote] 'permission' vote rewards require that the player be online. Set 'require-online' to 'true' in your configuration.
[16:29:59 WARN]: [SuperbVote] The 'chance' vote matcher will be switched to be based on percentages out of 100% in a future release. Use 'chance-fractional' to retain the current behavior, or migrate to a percentage matcher by specifying 'chance-percentage' in your configuration.

I know the above is my fault. But below is the random error.

[16:29:59 WARN]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[16:29:59 WARN]: SLF4J: Defaulting to no-operation (NOP) logger implementation
[16:29:59 WARN]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[16:29:59 ERROR]: Error occurred while enabling SuperbVote v0.4-BETA (Is it up to date?)
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.Gson.fromJson(Gson.java:899) ~[patched_1.12.2.jar:git-Paper-1322]
        at com.google.gson.Gson.fromJson(Gson.java:852) ~[patched_1.12.2.jar:git-Paper-1322]
        at io.minimum.minecraft.superbvote.storage.QueuedVotesStorage.<init>(QueuedVotesStorage.java:28) ~[?:?]
        at io.minimum.minecraft.superbvote.SuperbVote.onEnable(SuperbVote.java:53) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1322]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.2.jar:git-Paper-1322]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [patched_1.12.2.jar:git-Paper-1322]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:387) [patched_1.12.2.jar:git-Paper-1322]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:336) [patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292) [patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1322]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385) ~[patched_1.12.2.jar:git-Paper-1322]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183) ~[patched_1.12.2.jar:git-Paper-1322]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[patched_1.12.2.jar:git-Paper-1322]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[patched_1.12.2.jar:git-Paper-1322]
        ... 14 more

[16:29:59 INFO]: [SuperbVote] Disabling SuperbVote v0.4-BETA

[16:29:59 ERROR]: Error occurred while disabling SuperbVote v0.4-BETA (Is it up to date?)
java.lang.NullPointerException: null
        at io.minimum.minecraft.superbvote.SuperbVote.onDisable(SuperbVote.java:96) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.12.2.jar:git-Paper-1322]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344) [patched_1.12.2.jar:git-Paper-1322]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320) [patched_1.12.2.jar:git-Paper-1322]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [patched_1.12.2.jar:git-Paper-1322]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:387) [patched_1.12.2.jar:git-Paper-1322]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:336) [patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292) [patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1322]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]

**Comment by astei** [comment]
Delete `plugins/SuperbVote/queued_votes.json`
