### ISSUE TITLE
can you add placeholderapi top voter support?

### ISSUE THREAD

**Issue by Wqrld** [minecrafter/SuperbVote#44]
can you add support for placeholderapi to get the top 1-5 voters? I want to display my top voters in a hologram but that currently does not seem to be possible

**Comment by astei** [comment]
[It's already implemented](https://github.com/PlaceholderAPI/SuperbVote-Expansion/blob/master/src/main/java/com/extendedclip/papi/expansion/superbvote/SuperbVoteExpansion.java#L83).

Try using `%top_voter_name_<num>%`. For instance, ``%top_voter_name_3%` for the third-most votes.

**Comment by Wqrld** [comment]
doesn't seem to work for me
```
[17:06:39 INFO]: Wqrld issued server command: /papi parse %superbvote_top_voter_name_1%
[17:06:39 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'papi' in plugin PlaceholderAPI v2.8.5
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[paper.jar:git-Paper-1373]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[paper.jar:git-Paper-1373]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[paper.jar:git-Paper-1373]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1472) ~[paper.jar:git-Paper-1373]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1277) ~[paper.jar:git-Paper-1373]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[paper.jar:git-Paper-1373]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[paper.jar:git-Paper-1373]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[paper.jar:git-Paper-1373]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_172]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_172]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [paper.jar:git-Paper-1373]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [paper.jar:git-Paper-1373]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [paper.jar:git-Paper-1373]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [paper.jar:git-Paper-1373]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [paper.jar:git-Paper-1373]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_172]
        at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_172]
        at com.extendedclip.papi.expansion.superbvote.SuperbVoteExpansion.onPlaceholderRequest(SuperbVoteExpansion.java:89) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:201) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:178) ~[?:?]
        at me.clip.placeholderapi.commands.PlaceholderAPICommands.onCommand(PlaceholderAPICommands.java:207) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[paper.jar:git-Paper-1373]
        ... 15 more
```

**Comment by astei** [comment]
This is a bug in PlaceholderAPI. I've got a fix and clip ought to be pulling it soon.

**Comment by darbyjack** [comment]
Pulled. It will be push live shortly.

**Comment by darbyjack** [comment]
@astei Can you show me a screenshot of it working in game before I push it live in game? Thanks! You can also join the testplugins (clip and funnycubes) discord at http://testplugins.com/discord and tag me @Glare and I can work with you faster. Thanks again!

**Comment by astei** [comment]
@darbyjack Afraid I don't have the time to do that (school and such).

**Comment by Wqrld** [comment]
i can test it if you have a compiled extension for me to install.
